

CREATE TABLE IF NOT EXISTS public.users (
    id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    username VARCHAR(30) NOT NULL UNIQUE,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS public.quizzez (
  id integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  is_public BOOLEAN DEFAULT TRUE,

);

CREATE TABLE IF NOT EXISTS public.questions (

);

CREATE TABLE IF NOT EXISTS public.
